name: Build
run-name: Build Gradle Project on Push and Pull.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Clean Project
      uses: ./gradlew clean

    - name: Test Project
      uses: ./gradlew test

    - name: Build with Gradle
      run: ./gradlew build